---
driver:
  name: dokken
  chef_version: 12.19.36

transport:
  name: dokken

verifier:
  root_path: '/opt/verifier'
  sudo: false

provisioner:
  name: dokken
  log_level: info

platforms:
  - name: centos-6.8
    driver:
      image: centos:6.8
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/yum install -y sudo
  - name: centos-7.3
    driver:
      image: centos:7.3.1611
      privileged: true
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN /usr/bin/yum install -y sudo which
  - name: ubuntu-14.04
    driver:
      image: ubuntu:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update; /usr/bin/apt-get install -y sudo openssh-client software-properties-common
        - RUN /usr/bin/apt-add-repository ppa:openjdk-r/ppa -y
        - RUN /usr/bin/apt-get update; /usr/bin/apt-get -q -y install openjdk-8-jdk
        - RUN rm /usr/sbin/policy-rc.d; rm /sbin/initctl; dpkg-divert --rename --remove /sbin/initctl
      run_list:
        - recipe[apt]
  - name: ubuntu-16.04
    driver:
      image: ubuntu:16.04
      privileged: true
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install -y sudo openssh-client
      run_list:
        - recipe[apt]
