---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  log_level: info

platforms:
  - name: centos-6.8
  - name: centos-7.3
  - name: ubuntu-14.04
    run_list:
      - recipe[apt]
  - name: ubuntu-16.04
    run_list:
      - recipe[apt]

suites:
  - name: default
    run_list:
      - recipe[rundeck::server]
      - recipe[create_chef_dir]
      - recipe[rundeck::chef-rundeck]
    attributes:
      rundeck:
        hostname: localhost
        security_roles:
          - superusers
          - run_only_users
        api_client_config:
          # Logger::DEBUG
          log_level: 0
      domain: kitchentest
  - name: default-2.6.11
    run_list:
      - recipe[rundeck::server]
      - recipe[create_chef_dir]
      - recipe[rundeck::chef-rundeck]
    attributes:
      rundeck:
        rpm:
          version: rundeck-2.6.11-1.23.GA
        deb:
          package: rundeck-2.6.11-1-GA.deb
        checksum: 93e98ae0ef850756643e7f1dfb9f83432820485cac3a51c67fa5ef8039182d0b
        hostname: localhost
        security_roles:
          - superusers
          - run_only_users
        api_client_config:
          # Logger::DEBUG
          log_level: 0
      domain: kitchentest
  - name: default-2.8.3
    run_list:
      - recipe[rundeck::server]
      - recipe[create_chef_dir]
      - recipe[rundeck::chef-rundeck]
    attributes:
      rundeck:
        rpm:
          version: rundeck-2.8.3-1.32.GA
        deb:
          package: rundeck-2.8.3-1-GA.deb
        checksum: 694e893c01260139784d4b812c82005e530753603c80e5753307c26fc6fbc9f4
        hostname: localhost
        security_roles:
          - superusers
          - run_only_users
        api_client_config:
          # Logger::DEBUG
          log_level: 0
      domain: kitchentest
