language: ruby

cache: bundler

bundler_args: --retry 5

sudo: required

dist: trusty

rvm:
  - 2.3.1

env:
  - SUITE=chefspec
  - SUITE=lint
  - SUITE=default-centos-68
  - SUITE=default-269-centos-68
  - SUITE=default-centos-73
  - SUITE=default-269-centos-73
  - SUITE=default-ubuntu-1404
  - SUITE=default-269-ubuntu-1404
  - SUITE=default-ubuntu-1604
  - SUITE=default-269-ubuntu-1604

services:
  - docker

script:
  - bundle update
  - bundle exec ./.travis.sh

matrix:
  allow_failures:
    - env: SUITE=lint
    # We are allowing failure for Ubuntu 16. It keeps saying /sbin/status
    # doesn't exist when trying to restart the service rundeckd
    - env: SUITE=chefspec
  fast_finish: true
